---
kind: Service
apiVersion: v1
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  ports:
    - port: 4001
      name: config-server
      targetPort: 4001
  selector:
    app: config-server
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: config-server
spec:
  serviceName: "config-server"
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      imagePullSecrets:
        - name: $SECRET_NAME
      containers:
        - name: config-server
          image: $IMAGE_NAME
          ports:
            - containerPort: 4001
      initContainers:
        - name: init-myservice
          image: hub.medusa.com/library/curl_centos7:v1.0
          command: ['sh','-c','until [ "$(curl -I -o /dev/null -s -w %{http_code} http://eureka-0.eureka:10086/actuator/info)" -ge 200 ] && [ "$(curl -I -o /dev/null -s -w %{http_code} http://eureka-0.eureka:10086/actuator/info)" -le 400 ]; do echo waiting svc...; sleep 2; done;']
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: config-server
spec:
  rules:
    - host: spring-config.medusa.com
      http:
        paths:
          - path: /
            backend:
              serviceName: config-server
              servicePort: 4001