server:
  port: 3003
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: k8s-jms-eureka-server3003
eureka:
  instance:
    hostname: eureka3003.com
  client:
    region: CHINA
    availability-zones:
      CHINA: BJ,SH
    service-url:
      BJ: http://eureka3001.com:3001/eureka
      SH: http://eureka3002.com:3002/eureka
  server:
    #关闭自我保护机制,保证不可用服务被及时踢除
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 1000