server:
  port: 10086
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: k8s-jms-eureka-server3001
  profiles:
    active: prod

logging:
  level:
    com.netflix: warn

---
spring:
  profiles: dev
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
# 使用默认的 region
#    service-url:
#      defaultZone: http://eureka3001.com:3002/eureka,http://eureka3003.com:3003/eureka
# ---------------   自定义 region --------------------------
    region: CHINA
    availability-zones:
      CHINA: SH #,GZ
    service-url:
      SH: http://eureka3002.com:3002/eureka
#      GZ: http://eureka3003.com:3003/eureka
  server:
    #关闭自我保护机制,保证不可用服务被及时踢除
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 1000
    
---
spring:
  profiles: prod
eureka:
  server:
    # 续期时间,即扫描失效服务的间隔时间(缺省为60*1000ms)
    eviction-interval-timer-in-ms: 1000
    enable-self-preservation: false
    use-read-only-response-cache: false
  client:
    # eureka client间隔多久去拉取服务注册信息 默认30s
    registry-fetch-interval-seconds: 30
    serviceUrl:
      # 服务从 k8s pod 环境变量 获取
      defaultZone: ${EUREKA_SERVER:http://127.0.0.1:${server.port}/eureka/}
  instance:
    # 心跳间隔时间,即发送一次心跳之后,多久在发起下一次(缺省为30s)
    lease-renewal-interval-in-seconds: 30
    # 在收到一次心跳之后,等待下一次心跳的空档时间,大于心跳间隔即可,即服务续约到期时间(缺省为90s)
    lease-expiration-duration-in-seconds: 30
    instance-id: ${EUREKA_INSTANCE_HOSTNAME:${spring.application.name}}:${server.port}@${random.long(1000000,9999999)}
    hostname: ${EUREKA_INSTANCE_HOSTNAME:${spring.application.name}}
