---
kind: Service
apiVersion: v1
metadata:
  name: hystrix-provider
  labels:
    app: hystrix-provider
spec:
  ports:
    - port: 5001
      nodePort: 5111
      name: hystrix-provider
      targetPort: 5001
  type: NodePort
  selector:
    app: hystrix-provider
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: hystrix-provider
spec:
  serviceName: "hystrix-provider"
  replicas: 1
  selector:
    matchLabels:
      app: hystrix-provider
  template:
    metadata:
      labels:
        app: hystrix-provider
    spec:
      imagePullSecrets:
        - name: $SECRET_NAME
      containers:
        - name: hystrix-provider
          image: $IMAGE_NAME
          ports:
            - containerPort: 5001
      initContainers:
        - name: init-myservice
          image: hub.medusa.com/library/curl_centos7:v1.0
          command: ['sh','-c','until [ "$(curl -I -o /dev/null -s -w %{http_code} http://config-server-0.config-server:4001/actuator/info)" -ge 200 ] && [ "$(curl -I -o /dev/null -s -w %{http_code} http://config-server-0.config-server:4001/actuator/info)" -le 400 ]; do echo waiting svc...; sleep 2; done;']

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hystrix-provider
spec:
  rules:
    - host: hystrix-provider.medusa.com
      http:
        paths:
          - path: /
            backend:
              serviceName: hystrix-provider
              servicePort: 5001